### ISSUE TITLE
0.1 Home screen with beehives

### ISSUE THREAD

**Issue by 4chiAA** [4chiAA/capstone-beenabler#1]
## Value proposition

As an developer
I want to store beehives in a database and show them in the frontend
So that the user can see his beehives on the home page

## Description

![Image](https://github.com/4chiAA/capstone-beenabler/assets/149323651/d51b208b-c5ad-4424-9450-878a6752ab63)

## Acceptance criteria

- If there is no entry, display the text: "You don't have any beehives"

## Tasks

Backend:
- [x] implement the MongoDB in the backend
- [x] create the model beehive and a repository
- [x] create a service with a method to get the beehives and controller with a GetMapping

Frontend:

- [x] create a model beehive
- [x] create a page home page with the title "BeeNabler"
- [x] implement an axios.get to fetch the beehives and display them
