### ISSUE TITLE
delete beehive

### ISSUE THREAD

**Issue by 4chiAA** [4chiAA/capstone-beenabler#11]
## Value proposition

As an developer
I want a option to delete a single beehive
So that the user can remove beehives when they are no longer needed

## Description

![Image](https://github.com/4chiAA/capstone-beenabler/assets/149323651/6ae50796-5d5a-4c50-b376-feace103e854)

## Acceptance criteria

- [ ] Be clicking on the delete button, the user should get a pop-up window to delete the beehive or cancel

## Tasks

Backend:
- [ ] DeleteMapping for a single beehive with id

Frontend:
- [ ] create a pop-up window for deleting beehives
- [ ] implement the logic for the delete function
