### ISSUE TITLE
update beehive

### ISSUE THREAD

**Issue by 4chiAA** [4chiAA/capstone-beenabler#12]
## Value proposition

As an developer
I want a option to update a single beehive
So that the user can enter changes

## Description

![Image](https://github.com/4chiAA/capstone-beenabler/assets/149323651/85b693b6-67bb-4eaf-b699-da7327dd1a5a)

## Acceptance criteria

- [x] Be clicking on the update button, the user should get to a new page to update the beehive

## Tasks

Backend:
- [x] PutMapping for a single beehive with id and body

Frontend:
- [x] create a new page for updating beehives
- [x] implement the logic for the update function
