### ISSUE TITLE
02. Create beehive

### ISSUE THREAD

**Issue by 4chiAA** [4chiAA/capstone-beenabler#2]
## Value proposition

As an developer
I want a option to create a new beehive
So that the user can add new beehives to his app

## Description

![Image](https://github.com/4chiAA/capstone-beenabler/assets/149323651/8a51aaee-00ca-4be3-84b2-a0d617318b20)

## Acceptance criteria

- [x] A new page with input fields and the option to create or cancel

## Tasks

Backend:
- [x] Add a method in the service with the logic to add a new beehive
- [x] Add a PostMapping in the controller

Frontend:
- [x] A new Page with input fields
- [x] Cancel and create buttons
