### ISSUE TITLE
03. Show details of a beehive

### ISSUE THREAD

**Issue by 4chiAA** [4chiAA/capstone-beenabler#5]
## Value proposition

As an developer
I want a option to display a single beehive
So that the user can see the details of every beehive

## Description

![Image](https://github.com/4chiAA/capstone-beenabler/assets/149323651/221075fc-4cc8-4437-96d7-5f76db18a890)

## Acceptance criteria

- [x] Be clicking on the picture or the title, the user should get to the specific detail page

## Tasks

Backend:
- [x] GetMapping for a single beehive with id

Frontend:
- [x] create a new detail page for beehives
- [x] navigate to the detail page by clicking on the image or title on the home page
